app:
  name: 'go-clean-template'
  version: '1.0.0'

http:
  ip: 127.0.0.1
  port: 8848


logger:
  log_level: 'debug'
  rollbar_env: 'go-clean-template'


db:
  username: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  db_name: go_mall_admin
  timeout: 10s

oss:
  base_url: http://macro-oss.oss-cn-shenzhen.aliyuncs.com